CREATE TABLE members (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000001) PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000001) PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    isbn TEXT UNIQUE NOT NULL,
    available BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000001) PRIMARY KEY NOT NULL,
    member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    loan_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    return_date TIMESTAMPTZ,

    CONSTRAINT unique_active_loan UNIQUE (member_id, book_id, return_date),

    CONSTRAINT chk_return_after_loan CHECK (
        return_date IS NULL OR return_date >= loan_date
    )
);

INSERT INTO members (name, email) VALUES
('Anna Kovács', 'anna@example.com'),
('Béla Kiss', 'bela@example.com'),
('Cintia Farkas', 'cintia@example.com'),
('Dávid Horváth', 'david@example.com'),
('Erika Tóth', 'erika@example.com');

INSERT INTO books (title, author, isbn) VALUES
('1984', 'George Orwell', '9780451524935'),
('Brave New World', 'Aldous Huxley', '9780060850524'),
('Fahrenheit 451', 'Ray Bradbury', '9781451673319'),
('The Hobbit', 'J.R.R. Tolkien', '9780547928227'),
('To Kill a Mockingbird', 'Harper Lee', '9780061120084'),
('The Great Gatsby', 'F. Scott Fitzgerald', '9780743273565'),
('Moby Dick', 'Herman Melville', '9781503280786'),
('Pride and Prejudice', 'Jane Austen', '9781503290563'),
('The Catcher in the Rye', 'J.D. Salinger', '9780316769488'),
('Animal Farm', 'George Orwell', '9780451526342');

INSERT INTO loans (member_id, book_id, loan_date, return_date) VALUES
(1000001, 1000001, '2025-09-20 10:00:00+00', NULL),
(1000002, 1000002, '2025-09-18 12:30:00+00', '2025-09-25 09:00:00+00'),
(1000003, 1000003, '2025-09-10 14:00:00+00', NULL),
(1000004, 1000004, '2025-09-12 11:15:00+00', '2025-09-20 11:00:00+00'),
(1000005, 1000005, '2025-09-05 09:00:00+00', '2025-09-10 09:00:00+00'),
(1000001, 1000006, '2025-09-22 16:45:00+00', NULL),
(1000002, 1000007, '2025-09-15 10:00:00+00', NULL),
(1000003, 1000008, '2025-09-03 08:00:00+00', '2025-09-08 08:00:00+00'),
(1000004, 1000009, '2025-09-01 17:00:00+00', NULL),
(1000005, 1000010, '2025-08-25 13:00:00+00', '2025-09-01 13:00:00+00');