apiVersion: apps/v1
kind: Deployment
metadata:
  name: libro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libro
  template:
    metadata:
      labels:
        app: libro
    spec:
      containers:
      - name: libro
        image: libro:latest
        ports:
          - containerPort: 8000
        env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DB_NAME
            value: "libro"
          - name: DB_POOL_MIN_SIZE
            value: "1"
          - name: DB_POOL_MAX_SIZE
            value: "10"
          - name: API_PREFIX
            value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: libro-service
spec:
  type: ClusterIP
  selector:
    app: libro
  ports:
    - port: 8000
      targetPort: 8000
